spring:
  freemarker:
    enabled: true
    template-loader-path: classpath:/freemarker/

  devtools:
    add-properties: false

com:
  annwyn:
    niflheim:
      clean-path-at-startup: true
      template-engine: com.annwyn.niflheim.generator.engine.FreemarkerTemplateEngine
      column-registry: com.annwyn.niflheim.generator.configure.registry.MySQLColumnRegistry
      keyword-handle: com.annwyn.niflheim.generator.configure.keyword.MySQLKeywordHandle
      naming-strategy: com.annwyn.niflheim.generator.configure.naming.DefaultNamingStrategy
