spring:
  datasource:
    url: jdbc:mysql://47.100.211.129:3306/commerce?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Abcd1234#

com:
  annwyn:
    niflheim:
      output-directory: /Users/annwyn/workbench/workspace/annwyn/niflheim/output
      package-name: com.annwyn.test
      module-name: manager
      remove-prefixes:
        - tss_
      remove-suffixes:
        - tss_
      include-tables:
        - tss_*
