spring:
  freemarker:
    enabled: true
    template-loader-path: classpath:/freemarker/
  #  thymeleaf:
  #    prefix: classpath:/thymeleaf/
  #    mode: TEXT
  thymeleaf:
    enabled: false

  devtools:
    add-properties: false

com:
  annwyn:
    niflheim:
      template-engine: com.annwyn.niflheim.core.engine.FreemarkerTemplateEngine
      type-registry: com.annwyn.niflheim.core.registry.MysqlTypeRegistry
      clean-path-at-startup: true




