spring:
  freemarker:
    template-loader-path: classpath:/freemarker/
  #  thymeleaf:
  #    prefix: classpath:/thymeleaf/
  #    mode: TEXT

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.45.127.126:3306/eris?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Abcd1234#

com:
  annwyn:
    niflheim:
      template-engine: com.annwyn.niflheim.core.engine.FreemarkerTemplateEngine
      type-registry: com.annwyn.niflheim.core.registry.MysqlTypeRegistry

      output-directory: /Users/annwyn/workspace/development/niflheim/eris
      package-name: com.annwyn.eris.manager.mybatis
      exclusion-tables:
        - table1
      include-tables:
        - table2
      override-tables:
        - model-name: modelName
          table-name: tableName

      remove-suffixes:
        - table_suffix



